### ISSUE TITLE
OVERRIDING MEMBER

### ISSUE THREAD

**Issue by BrenoOR** [BrenoOR/GDI-2020.2-Telemedicina#67]
- [x] Done

**Comment by borrao** [comment]
-- 08. OVERRIDING MEMBER
-- Criando um tipo pessoa.
CREATE OR REPLACE TYPE tp_pessoa AS OBJECT (
  cpf VARCHAR2(14),
	nome VARCHAR2(30),
	idade NUMBER,
  MEMBER FUNCTION getIdentificacao RETURN VARCHAR2
) NOT FINAL;
/
-- Implementando a função getIdentificacao;
CREATE OR REPLACE TYPE BODY tp_pessoa AS
  MEMBER FUNCTION getIdentificacao RETURN VARCHAR2 IS
    BEGIN
      RETURN nome || ' - ' || idade || ' anos.';
    END;
END;
/
-- Criando um tipo médico que herda a função getIdentificacao de tp_pessoa e sobrescreve ela.
CREATE OR REPLACE TYPE tp_medico UNDER tp_pessoa (
  crm NUMBER,
  especialidade VARCHAR2(50),
  cpf_chefe VARCHAR2(14),
  OVERRIDING MEMBER FUNCTION getIdentificacao RETURN VARCHAR2
);
/
-- Implementando a função getIdentificacao para o tipo tp_medico.
CREATE OR REPLACE TYPE BODY tp_medico AS
  OVERRIDING MEMBER FUNCTION getIdentificacao RETURN VARCHAR2 IS
    BEGIN
      RETURN 'Dr. ' || nome || ' - CRM: ' || crm || '.';
    END;
END;
/
-- Testando o comportamento da função em um tipo pessoa e em um tipo médico.
DECLARE
  pess tp_pessoa;
  med tp_medico;
BEGIN
  pess := NEW tp_pessoa('581.051.853-57','Igor Mascarenhas', 20);
  DBMS_OUTPUT.PUT_LINE(pess.getIdentificacao);
  med := NEW tp_medico('025.105.198-45', 'João Kléber', 50, 3305, 'Endocrinologia', '256.941.852-06');
  DBMS_OUTPUT.PUT_LINE(med.getIdentificacao);
END;
/
